heat_dashboard/content/stacks/urls.py
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

from django.urls import re_path

from heat_dashboard.content.stacks import views

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^select_template$',
            views.SelectTemplateView.as_view(),
            name='select_template'),
    re_path(r'^launch$', views.CreateStackView.as_view(), name='launch'),
    re_path(r'^preview_template$',
            views.PreviewTemplateView.as_view(), name='preview_template'),
    re_path(r'^preview$', views.PreviewStackView.as_view(), name='preview'),
    re_path(r'^preview_details$',
            views.PreviewStackDetailsView.as_view(), name='preview_details'),
    re_path(r'^stack/(?P<stack_id>[^/]+)/$',
            views.DetailView.as_view(), name='detail'),
    re_path(r'^(?P<stack_id>[^/]+)/change_template$',
            views.ChangeTemplateView.as_view(), name='change_template'),
    re_path(r'^(?P<stack_id>[^/]+)/edit_stack$',
            views.EditStackView.as_view(), name='edit_stack'),
    re_path(r'^stack/(?P<stack_id>[^/]+)/(?P<resource_name>[^/]+)/$',
            views.ResourceView.as_view(), name='resource'),
    re_path(r'^get_d3_data/(?P<stack_id>[^/]+)/$',
            views.JSONView.as_view(), name='d3_data'),
]

heat_dashboard/content/stacks/forms.py
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import json
import logging

import django
from django.conf import settings
from django.template.defaultfilters import filesizeformat
from django.utils import html
from django.utils.translation import gettext_lazy as _
from django.views.decorators.debug import sensitive_variables

from oslo_utils import strutils

from horizon import exceptions
from horizon import forms
from horizon import messages

from heat_dashboard import api
from openstack_dashboard.dashboards.project.images \
    import utils as image_utils
from openstack_dashboard.dashboards.project.instances \
    import utils as instance_utils


LOG = logging.getLogger(__name__)


def image_field_data(request, include_empty_option=False):
    """Returns a list of tuples of all images.

    Generates a sorted list of images available. And returns a list of
    (id, name) tuples.

    :param request: django http request object
    :param include_empty_option: flag to include a empty tuple in the front of
        the list

    :return: list of (id, name) tuples

    """
    try:
        images = image_utils.get_available_images(
            request, request.user.project_id)
    except Exception:
        exceptions.handle(request, _('Unable to retrieve images'))
    images.sort(key=lambda c: c.name)
    images_list = []
    for image in images:
        image_label = u"{} ({})".format(image.name, filesizeformat(image.size))
        images_list.append((image.id, image_label))

    if not images:
        return [("", _("No images available")), ]

    if include_empty_option:
        return [("", _("Select Image")), ] + images_list

    return images_list


def create_upload_form_attributes(prefix, input_type, name):
    """Creates attribute dicts for the switchable upload form

    :type prefix: str
    :param prefix: prefix (environment, template) of field
    :type input_type: str
    :param input_type: field type (file, raw, url)
    :type name: str
    :param name: translated text label to display to user
    :rtype: dict
    :return: an attribute set to pass to form build
    """
    attributes = {'class': 'switched', 'data-switch-on': prefix + 'source'}
    attributes['data-' + prefix + 'source-' + input_type] = name
    return attributes


class TemplateForm(forms.SelfHandlingForm):

    class Meta(object):
        name = _('Select Template')
        help_text = _('Select a template to launch a stack.')

    # TODO(jomara) - update URL choice for template & environment files
    # w/ client side download when applicable
    base_choices = [('file', _('File')),
                    ('raw', _('Direct Input'))]
    url_choice = [('url', _('URL'))]
    attributes = {'class': 'switchable', 'data-slug': 'templatesource'}
    template_source = forms.ChoiceField(label=_('Template Source'),
                                        choices=base_choices + url_choice,
                                        widget=forms.ThemableSelectWidget(
                                            attrs=attributes))

    attributes = create_upload_form_attributes(
        'template',
        'file',
        _('Template File'))
    template_upload = forms.FileField(
        label=_('Template File'),
        help_text=_('A local template to upload.'),
        widget=forms.FileInput(attrs=attributes),
        required=False)

    attributes = create_upload_form_attributes(
        'template',
        'url',
        _('Template URL'))
    template_url = forms.URLField(
        label=_('Template URL'),
        help_text=_('An external (HTTP) URL to load the template from.'),
        widget=forms.TextInput(attrs=attributes),
        required=False)

    attributes = create_upload_form_attributes(
        'template',
        'raw',
        _('Template Data'))
    template_data = forms.CharField(
        label=_('Template Data'),
        help_text=_('The raw contents of the template.'),
        widget=forms.widgets.Textarea(attrs=attributes),
        required=False)

    attributes = {'data-slug': 'envsource', 'class': 'switchable'}
    environment_source = forms.ChoiceField(
        label=_('Environment Source'),
        choices=base_choices,
        widget=forms.ThemableSelectWidget(attrs=attributes),
        required=False)

    attributes = create_upload_form_attributes(
        'env',
        'file',
        _('Environment File'))
    environment_upload = forms.FileField(
        label=_('Environment File'),
        help_text=_('A local environment to upload.'),
        widget=forms.FileInput(attrs=attributes),
        required=False)

    attributes = create_upload_form_attributes(
        'env',
        'raw',
        _('Environment Data'))
    environment_data = forms.CharField(
        label=_('Environment Data'),
        help_text=_('The raw contents of the environment file.'),
        widget=forms.widgets.Textarea(attrs=attributes),
        required=False)

    referenced_files = forms.CharField(label=_('Referenced Files'),
                                       widget=forms.widgets.HiddenInput,
                                       required=False)

    if django.VERSION >= (1, 9):
        # Note(Itxaka): On django>=1.9 Charfield has an strip option that
        # we need to set to False as to not hit
        # https://bugs.launchpad.net/python-heatclient/+bug/1546166
        environment_data.strip = False
        template_data.strip = False

    def __init__(self, *args, **kwargs):
        self.next_view = kwargs.pop('next_view')
        super(TemplateForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned = super(TemplateForm, self).clean()

        files = self.request.FILES
        self.clean_uploaded_files('template', _('template'), cleaned, files)
        self.clean_uploaded_files('environment', _('environment'), cleaned,
                                  files)

        referenced_files = cleaned.get('referenced_files')
        if referenced_files:
            referenced_files = json.loads(referenced_files)
        elif referenced_files == '':
            referenced_files = {}

        # Validate the template and get back the params.
        kwargs = {}
        if cleaned['environment_data']:
            kwargs['environment'] = cleaned['environment_data']
        try:
            files, tpl =\
                api.heat.get_template_files(cleaned.get('template_data'),
                                            cleaned.get('template_url'),
                                            referenced_files)
            kwargs['files'] = files
            kwargs['template'] = tpl
            validated = api.heat.template_validate(self.request, **kwargs)
            cleaned['template_validate'] = validated
            cleaned['template_validate']['files'] = files
            cleaned['template_validate']['template'] = tpl
        except Exception as e:
            raise forms.ValidationError(str(e))

        return cleaned

    def clean_uploaded_files(self, prefix, field_label, cleaned, files):
        """Cleans Template & Environment data from form upload.

        Does some of the crunchy bits for processing uploads vs raw
        data depending on what the user specified. Identical process
        for environment data & template data.

        :type prefix: str
        :param prefix: prefix (environment, template) of field
        :type field_label: str
        :param field_label: translated prefix str for messages
        :type input_type: dict
        :param prefix: existing cleaned fields from form
        :rtype: dict
        :return: cleaned dict including environment & template data
        """
        upload_str = prefix + "_upload"
        data_str = prefix + "_data"
        url = cleaned.get(prefix + '_url')
        data = cleaned.get(prefix + '_data')

        has_upload = upload_str in files
        # Uploaded file handler
        if has_upload and not url:
            log_template_name = files[upload_str].name
            LOG.info('got upload %s', log_template_name)

            try:
                tpl = files[upload_str].read().decode('utf-8')
                if tpl.startswith('{'):
                    json.loads(tpl)
                cleaned[data_str] = tpl
            except Exception as e:
                msg = _('There was a problem parsing the'
                        ' %(prefix)s: %(error)s')
                msg = msg % {'prefix': prefix, 'error': str(e)}
                raise forms.ValidationError(msg)

        # URL handler
        elif url and (has_upload or data):
            msg = _('Please specify a %s using only one source method.')
            msg = msg % field_label
            raise forms.ValidationError(msg)

        elif prefix == 'template':
            # Check for raw template input - blank environment allowed
            if not url and not data:
                msg = _('You must specify a template via one of the '
                        'available sources.')
                raise forms.ValidationError(msg)

    def create_kwargs(self, data):
        kwargs = {'parameters': data['template_validate'],
                  'environment_data': data['environment_data']}
        if data.get('stack_id'):
            kwargs['stack_id'] = data['stack_id']
        return kwargs

    def handle(self, request, data):
        kwargs = self.create_kwargs(data)
        # NOTE (gabriel): This is a bit of a hack, essentially rewriting this

heat_dashboard/content/stacks/templates/stacks/_create.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}
{% block modal-body-right %}
  <h3>{% trans "Description:" %}</h3>
  <p>{% trans "Create a new stack with the provided values." %}</p>
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/_detail_topology.html
{% load i18n sizeformat %}

<div id="resource_container">
    <div id="info_box"></div>
    <div id="stack_box"></div>
    <div id="heat_resource_topology"></div>
    <div id="stack_id" data-stack_id="{{ stack_id }}"></div>
    <div id="d3_data" data-d3_data="{{ d3_data }}"></div>
</div>

heat_dashboard/content/stacks/templates/stacks/_preview_details.html
{% extends "horizon/common/_modal.html" %}
{% load i18n %}

{% block modal-header %}{% trans "Stack Preview" %}{% endblock %}

{% block modal-body %}
<div class="row-fluid stack-preview detail">
<form>
  <dl class="dl-horizontal">
    {% for key, value in stack_preview.items %}
      {% if key != 'parameters' and key != 'resources' and key != 'links' %}
        <dt>{{ key }}</dt>
        <dd>{{ value }}</dd>
      {% endif %}
    {% endfor %}
  </dl>

  {% if stack_preview.parameters %}
    <dt>{% trans "Parameters" %}</dt>
    <hr class="header_rule">
    <dl class="dl-horizontal">
      {% for key, value in stack_preview.parameters.items %}
        <dt>{{ key }}</dt>
        <dd>{{ value }}</dd>
      {% endfor %}
    </dl>
  {% endif %}

  {% if stack_preview.links %}
    <dt>{% trans "Links" %}</dt>
    <hr class="header_rule">
      {% for link in stack_preview.links %}
        <dl class="dl-horizontal">
        <dt>{{ link.rel }}</dt>
        <dd>{{ link.href }}</dd>
        </dl>
      {% endfor %}
  {% endif %}

  {% if stack_preview.resources %}
    <dt>{% trans "Resources" %}</dt>
      {% for resource in stack_preview.resources %}
        <hr class="header_rule">
        <dl class="dl-horizontal">
        {% for key, value in resource.items %}
          <dt>{{ key }}</dt>
          <dd>{{ value }}</dd>
        {% endfor %}
        </dl>
      {% endfor %}
  {% endif %}
</form>
</div>
{% endblock %}

{% block modal-footer %}
  <a href="{% url 'horizon:project:stacks:index' %}" class="btn btn-default cancel">{% trans "Close" %}</a>
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/_preview_template.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}
{% block form_attrs %}enctype="multipart/form-data"{% endblock %}
{% block modal-body-right %}
  <h3>{% trans "Description:" %}</h3>
  <p>{% trans "Use one of the available template source options to specify the template to be used in previewing this stack." %}</p>
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/_resource_info.html
<h3>{{ resource.resource_name }}</h3>

{% if resource.resource_status == 'CREATE_FAILED' %}
<p class="error">{{ resource.resource_status_desc }}</p>
<p class="error">{{ resource.resource_status_reason }}</p>
{% else %}
<p>{{ resource.resource_status_desc }}</p>
{% endif %}

<p>{{ resource.resource_type }}</p>

heat_dashboard/content/stacks/templates/stacks/_resource_overview.html
{% load i18n sizeformat %}

<div class="detail">
  <dl class="dl-horizontal">
    <dt>{% trans "Stack Resource ID" %}</dt>
    <dd>{{ resource.resource_name }}</dd>
    <dt>{% trans "Resource ID" %}</dt>
    <dd>
      {% if resource_url %}
      <a href="{{ resource_url }}">
          {{ resource.physical_resource_id }}
      </a>
      {% else %}
      {{ resource.physical_resource_id }}
      {% endif %}
    </dd>
    <dt>{% trans "Stack Resource Type" %}</dt>
    <dd>{{ resource.resource_type }}</dd>
    <dt>{% trans "Description" %}</dt>
    <dd>{{ resource.description }}</dd>
  </dl>

  <h4>{% trans "Status" %}</h4>
  <hr class="header_rule">
  <dl class="dl-horizontal">
    <dt>{% trans "Last Updated" %}</dt>
    <dd>{{ resource.updated_time|parse_isotime|timesince_or_never }}</dd>
    <dt>{% trans "Status" %}</dt>
    <dd>
      {% blocktrans with resource_status=resource.resource_status|title|replace_underscores resource_status_reason=resource.resource_status_reason %}{{ resource_status }}: {{ resource_status_reason }}{% endblocktrans %}
    </dd>
  </dl>

  <h4>{% trans "Resource Metadata" %}</h4>
  <hr class="header_rule">
  <pre>{{ metadata }}
  </pre>
</div>

heat_dashboard/content/stacks/templates/stacks/_select_template.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}
{% block form_attrs %}enctype="multipart/form-data"{% endblock %}
{% block modal-body-right %}
  <h3>{% trans "Description:" %}</h3>
  <p>{% trans "A template is used to automate the deployment of infrastructure, services, and applications." %}</p>
  <p>{% trans "Use one of the available template source options to specify the template to be used in creating this stack." %}</p>

  <script type="text/javascript">
      if (window.sessionStorage.generated == 'true'){
          $("#id_template_data").val(window.sessionStorage.getItem("template"));
          $("#id_referenced_files").val(window.sessionStorage.getItem("files"));
      }
      window.sessionStorage.setItem('generated', false);
      // window.sessionStorage.removeItem('template');

  </script>

{% endblock %}

heat_dashboard/content/stacks/templates/stacks/_stack_info.html
<img src="{{ stack_image }}" width="35px" height="35px" />
<div id="stack_info">
    <h3>{{ stack.stack_name }}</h3>
    <p class="error">{{ stack.stack_status_desc }}</p>
</div>
<div class="clear"></div>
{% if stack.stack_status == 'CREATE_FAILED' %}
    <p class="error">{{ stack.stack_status_reason }}</p>
{% endif %}
{% for output in stack.outputs %}
    {% if output.output_key == 'WebsiteURL' %}
    <a href="{{ output.output_value }}">{{ output.description }}</a>
    {% endif %}
{% endfor %}

heat_dashboard/content/stacks/templates/stacks/_update.html
{% extends "horizon/common/_modal_form.html" %}
{% load i18n %}
{% block modal-body-right %}
  <h3>{% trans "Description:" %}</h3>
  <p>{% trans "Update a stack with the provided values. Please note that any encrypted parameters, such as passwords, will be reset to default if you do not change them here." %}</p>
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/change_template.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Change Template" %}{% endblock %}

{% block main %}
  {% include 'project/stacks/_change_template.html' %}
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/preview.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Preview Stack" %}{% endblock %}

{% block main %}
  {% include 'project/stacks/_preview.html' %}
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/preview_details.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Preview Stack Details" %}{% endblock %}

{% block main %}
  {% include 'project/stacks/_preview_details.html' %}
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/select_template.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Select Template" %}{% endblock %}

{% block main %}
  {% include 'project/stacks/_select_template.html' %}
{% endblock %}

heat_dashboard/content/stacks/templates/stacks/update.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "Update Stack Parameters" %}{% endblock %}

{% block main %}
  {% include 'project/stacks/_update.html' %}
{% endblock %}